server:
  port: 8071
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/rgupta00/configfiles.git"
          clone-on-start: true
          default-label: main
          force-pull: true
          timeout: 5
